### ISSUE TITLE
Importing bug in unity

### ISSUE THREAD

**Issue by soulwax62** [mtschoen/JSONObject#1]
Hello!
I'm working on using a JSON file in unity. i'm really interested by your work.
sadly, I can't manage to import in Unity without facing a lot of issues. 
First error is that he refuses to read parameter specifier. If i define those parameters just after it works. But then I got other errors popping. Do you perhaps have some unity package that i can import in my unity?
![2015-03-11 10_55_51-assembly-csharp - c__users_imagine_documents_metroproject_assets_helpers_jsonobj](https://cloud.githubusercontent.com/assets/8017433/6600479/dde03fe4-c7dd-11e4-9635-78d6addacfa2.png)
Thank you very much for you help!
Soulwax

**Comment by mtschoen** [comment]
Hello there,

Do you actually get an error about this in the Unity Editor? If so, what version? I think this is jut something that MonoDevelop complains about, but not the Unity compiler.  Sorry for the confusion.

**Comment by soulwax62** [comment]
Hello Matt! sorry for the late answer,
I manage to make it work properly.
My only remaining problem is that after I use it in my project for a while
along with other scripts, the errors seems to reappear and block the editor
from compiling.
I precise that when I import the script and I modify other scripts around
it without touching it, Monodevelop detect the errors in JSON but I could
still launch the game without problems.
Do you have any idea for a long term use of the script without having to
reload the package and then remodify all the scripts?
Thank you
Matthieu

2015-03-11 11:28 GMT-05:00 Matt Schoen <notifications@github.com>:

**Comment by mtschoen** [comment]
Hey there,

What version of Unity are you using, and on what OS?  The reason that this hasn't been fixed is that in my 4+ years of using this script, I've never had any of these issues.  Someone a while back reported such a problem, but I haven't heard of this issue since then.  Also, what is the path to the JSON scripts within your project? They're not in the Editor, Plugins, or Standard Assets folders are they?

**Comment by soulwax62** [comment]
Ok after searching an answer to that problem i found out that by default
the compiler was set to Mono/.Net 3.5 which does'nt compile your JSON code.
If you are interrested by the change in case somebody ask you this question
again just follow this simple 2step tutorial.

You only have to change the projects settings

[image: alt text]

then go for general and choose.Net 4.0

This is it! Sorry for bothering you!

Matthieu


2015-03-12 14:44 GMT-05:00 Matthieu Antoniol <antoniol.matthieu@gmail.com>:

**Comment by mtschoen** [comment]
It looks like your image didn't upload properly. Is this project settings in MonoDevelop?  I've used Visual Studio since I started using Unity, so I guess that's why I never saw this!

**Comment by soulwax62** [comment]
Hi,
yes it was just an image of the path to project settings.
in the toolbar Project>Assembly-Csharp option.

By the way i'm using the last version Unity 5.0
thank you!


2015-03-12 15:23 GMT-05:00 Matt Schoen <notifications@github.com>:

**Comment by mtschoen** [comment]
If you're on Windows, I highly recommend Visual Studio ;)

**Comment by soulwax62** [comment]
I'm a begginer there and I started on Monodevelop it's basically all I know!

2015-03-12 15:31 GMT-05:00 Matt Schoen <notifications@github.com>:

**Comment by mtschoen** [comment]
Yeah it's OK. Visual Studio can be intimidating, but it's super nice to work with.  I'm pretty sure you can do whatever you need in Unity with the C# express edition (Windows Phone development aside).  It doesn't crash ever, doesn't have the slowness problem MD does (Find all references happens instantly), and has a LOT of nifty features.  When you have the time to try something new, definitely give it a try!

**Comment by mtschoen** [comment]
Closing this issue
