### ISSUE TITLE
Escaped slashes aren't unescaped at deserialization

### ISSUE THREAD

**Issue by melbic** [mtschoen/JSONObject#12]
In one of our jsons there are velocity values like `"16 km/h"`. The used serializer serializes it to `"16 km\/h"` which is a correct possibility according to json.org. Unfortunately JSONObject doesn't remove the trailing \ when deserializing the string.
A complete example of a json dictionary:

```
{
    "domains_detail": [1, 2, 3, 4],
    "status": 2,
    "wind_speed": "6 km\/h W",
    "id": "WD_001",
    "domains_overview": [1, 2, 3, 4],
    "wind_angle": 270,
    "temperature": "1°C",
    "domain_id": 1
}
```

**Comment by mtschoen** [comment]
Damn backslashes! Haha.  As you might see, that's the #1 issue type.  To be honest, I'm not sure that your issue is an issue.  From what I can tell, any JSON parser will include the backslash, since it's a part of the string.  Generally, you need to escape an actual backslash, as in \\, but I've never heard of \/.

What serializer are you using?

**Comment by melbic** [comment]
The standard iOS serializer` NSJSONSerialization` we use it for inApp communication ...

**Comment by mtschoen** [comment]
Ha! I should have known it would be an Apple product.  So I'm really not sure what to tell you.  Please feel free to fork this repo and add some extra processing that replaces \/ with /.  I'm not sure that it's appropriate as fix to the master branch.

**Comment by mtschoen** [comment]
Relevant: http://m.xkcd.com/1638/

**Comment by tivec** [comment]
Was there ever a fork and a patch for this? 

I've got JSON data with the following entry in it:
`"someEntry": "\"Quoted Text\""`

This comes out exactly identical without the \'s stripped when I get the .str for that particular entry. This might be a totally different issue to the one above, but shouldn't backslashes be stripped?

**Comment by cloudcover** [comment]
Related request: proper Unicode encoding. I've got JSON payloads with apostrophes, TM and (R) signs and they're all coming into Unity as proper Unicode and they come out on the other side of JSONObject as \uNNNN.

**Comment by mtschoen** [comment]
Hm. I wonder what's going on here. I don't believe that I transform the string in any way which should break unicode. Care to provide some sample data that breaks the parser?

**Comment by LispEngineer** [comment]
I have some string values that include embedded double quotes (e.g., strings that come over the wire like this: `"says \"User 80 Rocks\" on "`) that JSONObject renders with literal backslashes and double quotes. Clearly, escaping the double quotes is working, as the entire string comes through, but just as clearly the backslash escaping the double quote is remaining in the resulting string. Thoughts?

Thanks for JSONObject!

**Comment by mtschoen-unity** [comment]
Dealing with quotations and escaped characters is always tricky. My primary goal is for this tool to produce output that matches what _other_ JSON parsers put out to ensure reliable results.

What does your input data look like when it goes through other parsers. Can you a full example that illustrates your point, and what you would expect the resulting object to contain?

**Comment by mtschoen** [comment]
Dealing with quotations and escaped characters is always tricky. My primary goal is for this tool to produce output that matches what other JSON parsers put out to ensure reliable results.

What does your input data look like when it goes through other parsers. Can you a full example that illustrates your point, and what you would expect the resulting object to contain?

**Comment by LispEngineer** [comment]
(I will update this comment with more info as I generate it.)

Here is the JSON that is being generated by the server, both raw and pretty printed by `jq`:

```
$ curl --silent http://localhost:3000/room?player=80 ; echo
{"error":false,"room":{"name":"In Town","description":"This is the main town. You see a graveyard behind you, which feels all too familiar, even looking down upon it. You feel a chill down your back as you notice that one of the headstones says \"User 80 Rocks\" on it.","image":"desert"},"objects":{},"messages":[],"commands":[{"key":"north","label":"North","object-tag":"move","script":"move.clj","state":"move"},{"key":"south","label":"South","object-tag":"move","script":"move.clj","state":"move"},{"key":"east","label":"East","object-tag":"move","script":"move.clj","state":"move"},{"key":"west","label":"West","object-tag":"move","script":"move.clj","state":"move"}],"player":{"id":"80","location":[0,0],"name":"User 80 Rocks","gold":59}}
$ curl --silent http://localhost:3000/room?player=80 | jq
{
  "error": false,
  "room": {
    "name": "In Town",
    "description": "This is the main town. You see a graveyard behind you, which feels all too familiar, even looking down upon it. You feel a chill down your back as you notice that one of the headstones says \"User 80 Rocks\" on it.",
    "image": "desert"
  },
  "objects": {},
  "messages": [],
  "commands": [
    {
      "key": "north",
      "label": "North",
      "object-tag": "move",
      "script": "move.clj",
      "state": "move"
    },
    {
      "key": "south",
      "label": "South",
      "object-tag": "move",
      "script": "move.clj",
      "state": "move"
    },
    {
      "key": "east",
      "label": "East",
      "object-tag": "move",
      "script": "move.clj",
      "state": "move"
    },
    {
      "key": "west",
      "label": "West",
      "object-tag": "move",
      "script": "move.clj",
      "state": "move"
    }
  ],
  "player": {
    "id": "80",
    "location": [
      0,
      0
    ],
    "name": "User 80 Rocks",
    "gold": 59
  }
}
```

**Comment by LispEngineer** [comment]
Requested example given above.

**Comment by LispEngineer** [comment]
Submitted Pull Request: https://github.com/mtschoen/JSONObject/pull/21

**Comment by mtschoen** [comment]
This should be fixed in the latest version, and I've added unit tests to ensure this does not regress. EscapeString method is here 
https://github.com/mtschoen/JSONObject/blob/master/JSONObject.cs#L1033
