### ISSUE TITLE
Float weren't parsed correctly

### ISSUE THREAD

**Issue by shawhu** [mtschoen/JSONObject#14]
Json

```
{
"id": 186,
"device_name": "samsung SM-G900F db5a9b3e6036deb23e2491f29700045a",
"longitude": 121.00001,
"latitude": 31.00001
}
```

And when it's been tracked in the Unity Editor 

```
string result = System.Text.Encoding.UTF8.GetString (buffer); //<--this result is fine, it's identical to the json string above.
JSONObject obj = new JSONObject (result);  
         // ^ this obj is not. the latitude is still 31.00001 but the longitude is now 121. It loses precision.
```

How to fix it? Is it a bug?

**Comment by mtschoen** [comment]
You might try turning off "USEFLOAT," which is defined at the top of the file.  I'm assuming that you want to use floats universally, since that's what you do in game engines.  However, lat/lon values often require double precision, so I have a switch for it.

To be clear, just comment out #define USEFLOAT at the top of the file.  Let me know if that works.

**Comment by mtschoen** [comment]
Bump on this issue. Did using doubles work for you?

**Comment by kenmgrimm** [comment]
Hey,
Thanks for creating this tool.  I started by trying to use Unity Serialization + JSONUtility, why did I even think that that was a good idea...  

I ran into this same problem trying to decode lat and long in JSON using this library as well.  I did find the
`
#define USEFLOAT
`
and commented it out.  This leads to the following error:
`
Assets/Vendor/JSON/VectorTemplates.cs(220,144): error CS1502: The best overloaded method match for `UnityEngine.Keyframe.Keyframe(float, float)' has some invalid arguments
`
So I went in and "fixed" (I have no idea the repercussions of this) this issue in VectorTempates by changing the .n (double) to .f (float)
`
	public static Keyframe ToKeyframe(JSONObject obj){
		Keyframe k = new Keyframe(obj.HasField("time")? obj.GetField("time").f : 0, obj.HasField("value")? obj.GetField("value").f : 0);
		if(obj.HasField("inTangent")) k.inTangent = obj.GetField("inTangent").f;
		if(obj.HasField("outTangent")) k.outTangent = obj.GetField("outTangent").f;
		if(obj.HasField("tangentMode")) k.tangentMode = (int)obj.GetField("tangentMode").n;
		
		return k;
	}
`

Seems to work for parsing as I need but

**Comment by mtschoen** [comment]
Thanks for this fix! I ended up killing those templates to eliminate warnings in later Unity versions. Basically I decided it wasn't worth it to keep support for these features as the Unity API evolves.

Since the templates are now gone, the errors are gone! :)
