### ISSUE TITLE
hi~ im very very apreciate your JSONObject code , and i have question

### ISSUE THREAD

**Issue by littlewingsoft** [mtschoen/JSONObject#17]
i using  huge data ( about 3~4 mega )
when runtime parsing , very long time spended
so i found BakeAsync !!!
but i dont konw  BakeAsync 

i have question 2

1. how to use ?
2. how to know end of the BakeAsync ?

and this is my code

	IEnumerator co_test(){
		JSONObject tmpJo = JSONObject.CreateBakedObject ( veryBigData.text);
		Debug.Log ("begin");
		while (tmpJo.BakeAsync () != null) {
			Debug.Log (tmpJo.str );
			yield return null;
		}

		Debug.Log ("done");

	}

thanks for your Attention

**Comment by mtschoen** [comment]
Hi there. So you're actually using that figure backward.  I don't have a good way to create objects from string data in an asynchronous way.  Instead, you use this function https://github.com/mtschoen/JSONObject/blob/master/JSONObject.cs#L244 and specify a maxDepth and storeExcessLevels to true.  That will store data beyond a certain level of depth into a baked object.  I also don't have too much of a good way to parse that data once you need it in object form.

 If you are interested, I could try to improve this functionality in the future.

**Comment by littlewingsoft** [comment]
ok thanx~!
