### ISSUE TITLE
Handling of special characters

### ISSUE THREAD

**Issue by hrmoller** [mtschoen/JSONObject#19]
The following characters are not decoded when appearing in a string in the passed JSON:

`æ` - encoded as `\u00e6` 
`ø` - encoded as `\u00f8` 

(More to come😊)

**Comment by smruthykrishnan** [comment]
Were you able to solve this issue? If so please share the solution. I faced a similar issue:
I am trying to extract content from HTML file and construct a json from the extracted content. JSON created contains some special characters like \u0013 , \u0014, \u0007 etc. How to handle this?

**Comment by mtschoen-unity** [comment]
I believe that this is normal behavior. Simply call System.Regex.UnescapeString on the data either before processing or when you access it.  I'll double-check to make sure that the parser isn't transforming a single unicode character into this string, but I think this is just what happens when you put a unicode character through a .NET string.

**Comment by smruthykrishnan** [comment]
I am using java org.codehaus.jackson API to create json. I checked the extracted content from HTML. That looks fine. The special character comes up after converting the extracted content into jsonObject and saving it to a .json file

**Comment by mtschoen** [comment]
Could you send some sample data that reproduces the issue?

**Comment by smruthykrishnan** [comment]
[sampleHTML.txt](https://github.com/mtschoen/JSONObject/files/558144/sampleHTML.txt)
[sampleJSON.txt](https://github.com/mtschoen/JSONObject/files/558145/sampleJSON.txt)

I have attached sample html page and the resultant json.

**Comment by LispEngineer** [comment]
This should also be fixed by #21

**Comment by mtschoen** [comment]
I've made a bunch of updates and this should be handled. There is now an `EscapeString` and `UnescapeString` method to handle this scenario. I didn't handle unicode characters, but I think they should be preserved as-is. Feel free to re-open this PR if the issue persists on the latest version.

https://github.com/mtschoen/JSONObject/blob/master/JSONObject.cs#L1033
