### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pixtur** [mtschoen/JSONObject#23]
Hi, 

I love JSONObject and use it for some projects. I now want to integrate it into an open-source projects under M.I.T. license and was searching for your license information. 

It is possible to use and publish the code with a clear reference to the original source and this repo?

BR and thanks again for your great work.
Tom

**Comment by mtschoen-unity** [comment]
Hello. Yes, you may use the code and redistribute it however you like.  Please do give attribution where possible. I've played it pretty "fast and loose" with the license on this code. First it was LGPL until I realized how restrictive that was, and now it's MIT. I should probably mention that in the license.

**Comment by mtschoen** [comment]
Hello. Yes, you may use the code and redistribute it however you like.  Please do give attribution where possible. I've played it pretty "fast and loose" with the license on this code. First it was LGPL until I realized how restrictive that was, and now it's MIT. I should probably mention that in the license.
