### ISSUE TITLE
Error parsing float (when Globalization is set to german)

### ISSUE THREAD

**Issue by brean** [mtschoen/JSONObject#28]
```
string json = "{\"position\": [1.312, 4.606373506565475, -2.005028074709216]}";
JSONObject obj = new JSONObject(json);
Debug.Log(obj.GetField("position")[0]);
```
outputs `1312`. 
This is a localization bug, because in Germany we use "," instead of "." as separation:
```
Debug.Log(System.Convert.ToSingle("1,123")); // Outputs 1,123
Debug.Log(System.Convert.ToSingle("1.123")); // Outputs 1123
```

**Comment by mtschoen** [comment]
Go for it

**Comment by Piggspigg** [comment]
I would like to add that it's not only the parsing that is affected by the float to string / string to float conversions. It's also the serialization.
This means that if you would serialize the objects with German cultural settings you would not be able to parse the output. Even worse, it succeeds, but with the incorrect values in the resulting JSONObject.

Ex:
{"value1" : 1.5, "value2" : 2.5} 
...is serialized into...
{"value1" : 1,5, "value2" : 2,5} 
...which in turn is parsed as...
{"value1" : 1, "value2" : 2} 

I do not have time to make a pull request right now, but the issues can be found on line 737, 938 and 1079. Where the following needs to be changed:

builder.Append(n.ToString());
...should be...
builder.Append(n.ToString(System.Globalization.CultureInfo.InvariantCulture));

and

case Type.NUMBER: result.Add(keys[i], val.n + ""); break;
...should be...
case Type.NUMBER: result.Add(keys[i], val.n.ToString(System.Globalization.CultureInfo.InvariantCulture)); break;
