### ISSUE TITLE
Can't build when the platform is Windows Store

### ISSUE THREAD

**Issue by trlanfeng** [mtschoen/JSONObject#3]
Assets\JSON\JSONObject.cs(250,8): error CS1502: �롰string.Compare(string, string, System.StringComparison)����ƥ�������ط�������һЩ��Ч����

Assets\JSON\JSONObject.cs(250,36): error CS1503: ���� 3: �޷��ӡ�bool��ת��Ϊ��System.StringComparison��

....

When the platform is " Windows Store " , the project can't build .

**Comment by mtschoen** [comment]
Hi there. I've just committed a fix for this.  I had a preprocessor switch for Win Phone 8 which had the same issue, but I hadn't thought to include Win Store. If this still doesn't work, we just have to find the right platform define as listed here:
http://docs.unity3d.com/Manual/PlatformDependentCompilation.html
