### ISSUE TITLE
Warning for obsolete code

### ISSUE THREAD

**Issue by brean** [mtschoen/JSONObject#33]
In Unity 2018 .Net 4.x will be stable (I am currently using the beta)
This means `UnityEngine.Keyframe.tangentMode` will be obsolete. We should switch to `AnimationUtility.SetLeftTangentMode`, `AnimationUtility.SetRightTangentMode`, `AnimationUtility.GetLeftTangentMode` or `AnimationUtility.GetRightTangentMode` instead.

**Comment by arduzj** [comment]
so, how do we solve it?

**Comment by WillbKool** [comment]
Yes, pray tell, how do we fix it? ;)

**Comment by brean** [comment]
Instead of just storing one tangentMode for both sides of the Keyframe we should save two for each side of the keyframe. I propose just adding "leftTangent" and "rightTangent" to the JSON and then call SetRightTangentMode. I am not that firm with the Animation/Keyframe part of the Unity-API, but I can create a small fix this week.

**Comment by mtschoen-unity** [comment]
Considering that code was written like 5+ years ago, I'm shocked that we're only *just* running into compatibility warnings :)

There's almost certainly *new* stuff that's missing.

What I would advise is to use #if UNITY_VERSION defines to block out and add-in the fields you need. I'd be happy to look at a PR to fix the current warning.

**Comment by brean** [comment]
I have to admit I don't know enough about animations to provide a fix. `SetKeyLeftTangentMode` requires an `AnimationCurve`. This `AnimationCurve` needs a list of keyframes, but I only have one keyframe, so I don't know how to serialize this the right way.

**Comment by mtschoen** [comment]
I've decided it's not worth it to worry about this in this repo. If someone decides it's useful to share a version of these templates that fully supports "recent" Unity versions, feel free. I've merged in some changes that just delete these templates, thus avoiding this issue :)
