### ISSUE TITLE
[proposal] (Unit-)Tests

### ISSUE THREAD

**Issue by brean** [mtschoen/JSONObject#34]
I think it would be extremely helpful if we had some Unit-tests, especially for lesser-used functions like Animation/Keyframe serialization and special characters.

**Comment by mtschoen** [comment]
I welcome your PR with tests :)

I haven't been using this library in any of my recent projects, but if/when I do, I will take some time to add some tests. For now, the best way to test is to use the JSONChecker window, either by pasting your input into it, or a URL that responds with JSON to a GET request.

Note that per a few of my other comments recently, the Animation/Keyframe templates have been removed.
