### ISSUE TITLE
[solution] for #POOLING "wtf/wtflist" problem

### ISSUE THREAD

**Issue by OndrishD** [mtschoen/JSONObject#36]
### Issue
I have noticed that pooling has some issues with NULL references in releaseQueue. I was able to reproduce this problem almost every time when parsing larger json. 

The issue is that adding the reference back to releaseQueue in object destructor is NOT enough. GC might not recheck references anymore and that is the reason why pooled objects are lost in releaseQueue (GCed).

### Solution
You have to tell explicitly to GC that you messed with reference of a object that is about to get removed completely by calling `System.GC.ReRegisterForFinalize(obj);`

This might cause destructor to run twice so you have to add a flag indicating that object was already added to pool `private bool isPooled;` Set this variable to true when object is Queued and to false when Dequeued.
_NOTE: I also added lock just because I am parsing on concurrent threads._
```c# 
private bool isPooled = false;
```
```c#
public static JSONObject Create() {
#if POOLING
	JSONObject result = null;
        lock (releaseQueue)
        {
            while (result == null && releaseQueue.Count > 0)
            {
                result = releaseQueue.Dequeue();
#if DEV
		//The following cases should NEVER HAPPEN (but they do...)
                if(result == null)
                   Debug.WriteLine("wtf " + releaseQueue.Count);
		else if(result.list != null)
		   Debug.WriteLine ("wtflist " + result.list.Count);
#endif
            } 
        }
        if (result != null)
        {
            result.isPooled = false;
            return result;
        }
#endif
	return new JSONObject();
}
```
```c#
~JSONObject() {
	if(pool && !isPooled && releaseQueue.Count < MAX_POOL_SIZE) {
			type = Type.NULL;
			list = null;
			keys = null;
			str = "";
			n = 0;
			b = false;
            isPooled = true;
            lock (releaseQueue)
            {
                releaseQueue.Enqueue(this); 
            }
            System.GC.ReRegisterForFinalize(this);
        }
}
```

After applying these changes I have not encountered "wtf/wtflist" log messages anymore caused by NULL dequeued from releaseQueue.

**Comment by mtschoen-unity** [comment]
Thanks! I'll take a look at this when I have the chance. It's been so long since I used this code in production that I might just have to take your word for it. I've been meaning to do a bunch of cleanup so this will be a good excuse to do so!

**Comment by mtschoen** [comment]
Thanks! I'll take a look at this when I have the chance. It's been so long since I used this code in production that I might just have to take your word for it. I've been meaning to do a bunch of cleanup so this will be a good excuse to do so!

[Sorry for the double-post. Used the wrong account :]

**Comment by mtschoen** [comment]
I've implemented this solution in the latest version. Let me know if the issue persists
