### ISSUE TITLE
[Localization] Serializing JSONObject yields the incorrect result in different cultural regions

### ISSUE THREAD

**Issue by Piggspigg** [mtschoen/JSONObject#37]
Related to the previously mentioned problems with float/string conversions with different cultural settings (German for example).

I would like to add that it's not only the parsing that is affected by the float to string / string to float conversions. It's also the serialization (Stringfy(...)) of JSONObject.
This means that if you would serialize the objects with German cultural settings you would not be able to parse the output. Or even worse, the parsing succeeds, but with the incorrect values in the resulting JSONObject.

Ex:
```
{"value1" : 1.5, "value2" : 2.5} 
//is serialized into
{"value1" : 1,5, "value2" : 2,5} 
//which in turn is parsed as
{"value1" : 1, "value2" : 2} 
```

I do not have time to make a pull request right now, but the issues can be found on line 737, 938 and 1079. Where the following needs to be changed:

```
builder.Append(n.ToString());
//should be
builder.Append(n.ToString(System.Globalization.CultureInfo.InvariantCulture));
```

and

```
case Type.NUMBER: result.Add(keys[i], val.n + ""); break;
//should be
case Type.NUMBER: result.Add(keys[i], val.n.ToString(System.Globalization.CultureInfo.InvariantCulture)); break;
```

**Comment by mtschoen** [comment]
Thanks for the bug report! I've updated the master branch to use Invariant Culture everywhere, and get rid of some of those pesky `+ ""`. I didn't know any better at the time, but it allocates memory when it doesn't need to!

Fixed in 077a293
