### ISSUE TITLE
Wrong conversion depending on CulturalInfo

### ISSUE THREAD

**Issue by Kyrw** [mtschoen/JSONObject#43]
On different machines numbers are being converted in different formats. 

the number 26.643470764160158 (using float conversion), on my machine is serialized as 26.64347
but on another machine it was serialized as 2.6xxxE+16. This wouldnt be a problem but when converting back, it ingores the notation, returning 2.6xxx. 

To fix this i needed to use 
System.Globalization.CultureInfo.DefaultThreadCurrentCulture = System.Globalization.CultureInfo.InvariantCulture;

System.Globalization.CultureInfo.DefaultThreadCurrentUICulture** = System.Globalization.CultureInfo.InvariantCulture;

You can add this on JSONObject class, or on each method of System.Convert, call for CultureInfo.InvariantCulture as the second parameter.

Sorry for the rushed post, I'm in a hurry on my project, but wanted to at least let you guys know. 
Regards

**Comment by zadinvit** [comment]
I had same problem, my program parse "0.05" as null, i fix this with added cultural info to convert functions. 

Example

`n = System.Convert.ToSingle(str,System.Globalization.CultureInfo.InvariantCulture);`

**Comment by mtschoen** [comment]
This seems to only be an issue with the Asset Store version. It was fixed on GitHub a while ago. I've made a bunch of updates and double-checked that we're using CultureInfo. I'll be updating AssetStore shortly.
