### ISSUE TITLE
Unescaped characters when downloading from certain servers

### ISSUE THREAD

**Issue by BlustFizbin** [mtschoen/JSONObject#45]
We had a problem that certain strings were downloaded as unescaped strings and gave us back text where the **'** was displayed as **\n27** and **"** as **\"** .

W fixed it by changing the lines
`obj.str = val;`
to
`obj.str = Regex.Unescape(val);`

This would be great to either have ist be enabled as an option or as a default as I don't think many want unescaped strings.

Thanks for the work you do :)

**Comment by mtschoen** [comment]
Can you check what happens on the latest version? I added a method for `UnEscapeString` because I'm not sure that `Regex.Unescape` does exactly what we want.
