### ISSUE TITLE
BSD License?

### ISSUE THREAD

**Issue by pauley-unsaturated** [mtschoen/JSONObject#8]
Would it be possible for you to convert this to BSD or similarly permissive license please? If I understand correctly, LGPL would restrict usage of this lib in situations where you must statically link (like iOS).

**Comment by mtschoen** [comment]
Yep! I picked LGPL kind of off-the-cuff many years ago just to have a license in the first place.  What do you think about MIT license?

**Comment by pauley-unsaturated** [comment]
I like that one too.  Apache, MIT and BSD are great for devs.

**Comment by pauley-unsaturated** [comment]
BSD is nicer because no attribution is necessary, but MIT works too.

**Comment by pauley-unsaturated** [comment]
Also: you can't just post a link to the license.  
Please post the full license both in the readme and at the top of each file as described here:

https://en.wikipedia.org/wiki/BSD_licenses
https://en.wikipedia.org/wiki/MIT_License

2-clause BSD or MIT license is great.
