### ISSUE TITLE
Array parsing issue

### ISSUE THREAD

**Issue by thetylerwolf** [mtschoen/JSONObject#9]
Hi, I'm having trouble parsing an array. The object is recognized as key - "sculptures", but the array is recognized as type string. Nothing I try will get around this. The object looks like this:

{"sculptures": "[{\"fields\": {\"id\": 1, \"viewable\": true, \"date_added\": \"2015-10-27T18:35:30Z\"}, \"model\": \"server.sculpture\", \"pk\": 1}]"}

This json has been validated with jsonlint

**Comment by thetylerwolf** [comment]
I finally figured it out. The " before the square brackets is the issue. The backend I'm using serializes arrays with quotes, so they need to be removed. Also, the escaped quotes needed to be turned to regular quotes. I leave it to you whether or not to consider that an actual issue :)

**Comment by mtschoen** [comment]
Yeah I'm gonna file this under "not an issue." haha.  The quotes around your array do, indeed, mean that it's interpreted as a string, and not JSON.  In fact, there are special steps I had to take to ensure that this was the case (ignoring escaped quotes within the string).  Also, if you remove the outer quotes, JSONLint also complains about the escaped quotes within it.  All of this is the desired behavior.
